# Generated by Django 5.0.10 on 2024-12-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_alter_driver_email_alter_driver_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
